### ISSUE TITLE
Fix Spelling Errors

### ISSUE THREAD

**Issue by threedot14** [mhsengineering/mhsengineering.github.io#1]
The website content should probably be put in a google doc and edited before being put on the live website. Some of the spelling errors have already been fixed (commit ef5aa62894914e2f67d526ad40c75f13c79628b4), but many still remain.

**Comment by 50Wliu** [comment]
Since when this issue was created all spelling issues seemed to have been fixed and a proper system of pull requests should prevent any more serious ones from popping up, I'm closing this issue.

(@threedot14 wrote this)
