### ISSUE TITLE
Fix Formatting

### ISSUE THREAD

**Issue by threedot14** [mhsengineering/mhsengineering.github.io#2]
From Ms. Kolker:
> [please fix] formatting on home page - make picture smaller so that visitors can see that there is text below.  and reduce font on text so it fits inside the boxes

**Comment by threedot14** [comment]
The Contact page is the biggest offender.
![screenshot 2015-11-17 at 1 52 42 pm](https://cloud.githubusercontent.com/assets/1761259/11221320/854b4fde-8d32-11e5-8478-879b7292a7e7.png)

**Comment by mhsengineeringboard** [comment]
Oh alright, we will consider that.

On Tue, Nov 17, 2015 at 1:53 PM, Eric Roberts <notifications@github.com>
wrote:

> The Contact page is the biggest offender.
> [image: screenshot 2015-11-17 at 1 52 42 pm]
> <https://cloud.githubusercontent.com/assets/1761259/11221320/854b4fde-8d32-11e5-8478-879b7292a7e7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mhsengineering/mhsengineering.github.io/issues/2#issuecomment-157469435>
> .
>



-- 
*Best Regards,*

*Loving Members of the Board*

-- 
*This email and any attached information (“email”) is confidential and 
intended solely for the use of the individual or entity to whom they are 
addressed in the body of the email. This email may contain information that 
is privileged, confidential and prohibited from disclosure or unauthorized 
use under applicable law.  If you are not the intended recipient or person 
responsible for delivering this email to the intended recipient, you have 
received this communication in error, and any review, use, disclosure, 
dissemination, forwarding, printing, copying, distribution or taking any 
action in reliance on this email is strictly prohibited.  If you have 
received this email in error please immediately notify the system manager, 
sender or the Morris School District by telephone or email and permanently 
delete the original email and remove all copies from your system.*

**Comment by threedot14** [comment]
The Contact page has been fixed (commit fa2ab8030544247b2c131c2d688e8d0922c78a0c) but other formatting issues still remain.

**Comment by johntheawesomeguy** [comment]
are there any remaining formatting issues on the current site or can we close this?
