### ISSUE TITLE
Transfer the website to the successor

### ISSUE THREAD

**Issue by three** [mhsengineering/mhsengineering.github.io#27]
I will be leaving for college next year and will not be able to continue running the mhsengineering.club website. Sometime in the next few months I will need to transfer everything.

The following services are used to run mhsengineering.club:
- **Namecheap** - The domain registrar. Costs $10/year. This is what allows us to point the mhsengineering.club domain where we want.
- **Cloudflare** - DNS and Proxy. We primarily use Cloudflare for HTTPS support, otherwise we could point Namecheap directly to Github (using Namecheap's DNS).
- **Github** - Host and serve content on www.mhsengineering.club.
- **updog.co** and **Dropbox** - Provide free static image hosting on dns.mhsengineering.club. This service is heavily cached by Cloudflare. We don't want to put images directly in the main repo for space concerns, so this is the best static hosting I could find for free.

All of the above services need to be transferred by the end of the school year.

**Comment by 50Wliu** [comment]
I think this happened.
