### ISSUE TITLE
Universal font and other agreement issues

### ISSUE THREAD

**Issue by johntheawesomeguy** [mhsengineering/mhsengineering.github.io#9]
We need to all agree as a group on one font. Also I noticed that some people are changing things for the sake of changing things without adding anything meaningful to the site. I think we should agree not to mess with the styling sheet unless we are fixing formatting errors or doing something that actually contributes to the site instead of just slightly changing the values for padding and font size.

**Comment by 50Wliu** [comment]
PRs are now required so this shouldn't happen again.

**Comment by mhsengineeringboard** [comment]
comic sans

On Mon, Nov 23, 2015 at 10:56 AM, johntheawesomeguy <
notifications@github.com> wrote:

> We need to all agree as a group on one font. Also I noticed that some
> people are changing things for the sake of changing things without adding
> anything meaningful to the site. I think we should agree not to mess with
> the styling sheet unless we are fixing formatting errors or doing something
> that actually contributes to the site instead of just slightly changing the
> values for padding and font size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mhsengineering/mhsengineering.github.io/issues/9>.
>



-- 
*Best Regards,*

*Loving Members of the Board*

-- 
*This email and any attached information (“email”) is confidential and 
intended solely for the use of the individual or entity to whom they are 
addressed in the body of the email. This email may contain information that 
is privileged, confidential and prohibited from disclosure or unauthorized 
use under applicable law.  If you are not the intended recipient or person 
responsible for delivering this email to the intended recipient, you have 
received this communication in error, and any review, use, disclosure, 
dissemination, forwarding, printing, copying, distribution or taking any 
action in reliance on this email is strictly prohibited.  If you have 
received this email in error please immediately notify the system manager, 
sender or the Morris School District by telephone or email and permanently 
delete the original email and remove all copies from your system.*
